# Generated by Django 2.1.2 on 2018-10-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('repeat_inf', models.BooleanField(default=False)),
                ('repeat_times', models.IntegerField()),
                ('repeat_freq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('day', models.DateField()),
                ('repeat_inf', models.BooleanField(default=False)),
                ('repeat_times', models.IntegerField()),
                ('repeat_freq', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(to='oneliner.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(to='oneliner.Task'),
        ),
    ]
