# Generated by Django 2.1.2 on 2018-10-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0002_auto_20181015_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
    ]
