# Generated by Django 2.1.2 on 2018-10-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0004_auto_20181015_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
