# Generated by Django 2.1.2 on 2018-10-17 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='day',
            new_name='date',
        ),
    ]
