# Generated by Django 2.1.2 on 2018-10-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0007_auto_20181017_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(to='oneliner.Event'),
        ),
    ]
