# Generated by Django 2.1.5 on 2019-01-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0008_profile_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
