# Generated by Django 2.1.5 on 2019-02-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0009_auto_20190131_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
